(** Error functions for jsonaf conversions.

    All functions in this module raise exceptions and are intended to be called only by
    code generated by [ppx_jsonaf_conv]. They should not be called directly. *)

(** Raised when no variant matches during polymorphic variant parsing. *)
exception No_variant_match

(** The location string generated by the ppx, typically of the form
    ["module_path.type_name"]. *)
type loc := string

[%%template:
[@@@mode.default m = (global, local)]

(** {2 Errors concerning tuples} *)

val tuple_of_size_n_expected : loc -> int -> Jsonaf_kernel.t @ m -> _

(** {2 Errors concerning sum types} *)

val stag_no_args : loc -> Jsonaf_kernel.t @ m -> _
val stag_incorrect_n_args : loc -> string @ m -> Jsonaf_kernel.t @ m -> _
val stag_takes_args : loc -> Jsonaf_kernel.t @ m -> _
val nested_list_invalid_sum : loc -> Jsonaf_kernel.t @ m -> _
val empty_list_invalid_sum : loc -> Jsonaf_kernel.t @ m -> _
val unexpected_stag : loc -> Jsonaf_kernel.t @ m -> _

(** {2 Errors concerning records} *)

val format_superfluous_fields : what:string -> loc:loc -> string list @ m -> string
val record_duplicate_fields : loc -> string list @ m -> Jsonaf_kernel.t @ m -> _
val record_extra_fields : loc -> string list @ m -> Jsonaf_kernel.t @ m -> _

val record_undefined_elements
  :  loc
  -> Jsonaf_kernel.t @ m
  -> (bool * string) list @ m
  -> _

val record_list_instead_atom : loc -> Jsonaf_kernel.t @ m -> _
val record_poly_field_value : loc -> Jsonaf_kernel.t @ m -> _

(** {2 Errors concerning polymorphic variants} *)

val no_variant_match : unit -> _
val no_matching_variant_found : loc -> Jsonaf_kernel.t @ m -> _
val ptag_no_args : loc -> Jsonaf_kernel.t @ m -> _
val ptag_incorrect_n_args : loc -> string @ m -> Jsonaf_kernel.t @ m -> _
val ptag_takes_args : loc -> Jsonaf_kernel.t @ m -> _
val nested_list_invalid_poly_var : loc -> Jsonaf_kernel.t @ m -> _
val empty_list_invalid_poly_var : loc -> Jsonaf_kernel.t @ m -> _
val empty_type : loc -> Jsonaf_kernel.t @ m -> _]
